# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 917ad12b7bbaf2649617c1accdf63061459f83ca8947bad162dd6d609841be0e9c8761c805ea2ced7628ac303b294681cbad70a5fb4e8407a818ceffc4da119e

test:
  secret_key_base: 8bca3832a77c7fe2f0c7b4bcbc93d32e4799117e373602c44a31c3fd594a5b64ce703d730aa502cd27ec89e5f580c724f8a4328aaee10aebaa1793678578be3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
